---
title: "Group 19 UCSB domestic grad enrollment"
author: "Emily Pelstring, Chance English"
date: "11/16/2021"
output: html_document
---

## Set Up
```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(here)
library(tidyverse)
```

## Reading in the Data 

```{r}
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```



## Visualize Domestic Graduate Enrollment from 2008-2019

```{r}

ucsb_grad %>% 
  ggplot(aes(x = year_abbr, y = domestic_enrollment)) +
  geom_col(aes(fill = ethnicity),
           position = "fill") +
  labs(x = "Year",
       y = "Proportion of Enrollment",
       title = "UCSB Domestic Graduate Student Enrollment by Race/Ethnicity (2008-2019)") +
  theme_minimal()


```
**Figure 1.** Figure 1. The percent contribution of racial/ethnic groups to the total domestic graduate school enrollment at UCSB each year from 2008-2019.data source: University of California, Santa Barbara Office of Budget and Planning
